server:
   port: 8001

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml
   type-aliases-package: com.atguigu.springcloud.entities
   mapper-locations:
   - classpath:mybatis/mapper/**/*.xml

spring:
   application: 
      name: microservicecloud-dept
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://120.79.78.185:3306/cloudDB01
      username: root
      password: World*zero05
      dbcp2:
         min-idle: 5
         initial-size: 5
         max-total: 5
         max-wait-millis: 200
         
eureka:
   client: #客户端注册金eureka服务列表内
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
   instance:
      instance-id: provid-8001 #主机映射名称修改
      prefer-ip-address: true  #主机ip信息显示
      
info:
   app.name: atguigu-microservicecloud
   company.name: www.atguigu.com
   build.artifactId: $project.artifactId$
   build.version: $project.version$